---
- hosts: all
  vars_prompt:
    - name: "is_true"
      prompt: "Entrer votre valeur true ou false"
      private: yes
  tasks:
    - name: create file
      file: state=touch path=/home/{{ansible_ssh_user}}/xyz.conf
      when: is_true == "true"

